### ISSUE TITLE
Koalify the slides

### ISSUE THREAD

**Issue by angrykoala** [demiurgosoft/brujeria-con-node#6]
koalify the slides and generate using yamp

**Comment by aledomu** [comment]
Do you want the generate pipeline as well or just the result?

**Comment by angrykoala** [comment]
the pipeline would be cool. However im not sure if this is worth it doing tbh

**Comment by aledomu** [comment]
I already did it, just needs these steps as I implemented it to modify the slides:
1. `git clone (url)`
2. `npm install`
3. Modify markdown files, then `npm generate` (here it is koalified)
4. `npm clean`, then `git push`

Tell me if you agree with this and I'll quickly send the PR with the modifications and documenting how it is used in the README.

**Comment by angrykoala** [comment]
Make the PR, I'll check if everything is ok, you don't have to worry :)
Thanks
